export const translations = {
  en: {'nav.about':'About','nav.projects':'Projects','nav.contact':'Contact','nav.pdf':'Download PDF','hero.eyebrow':'Technical artist · graphics engineer · aspiring VJ','hero.lede':'I make games, creative tools and artcode.','hero.roles':'game development · design · computer graphics','hero.cta':'See projects <span aria-hidden="true" class="arrow arrow-down"></span>','hero.contact':'Say Hello :) <span aria-hidden="true" class="arrow arrow-up"></span>','section.about':'01 / about','section.projects':'02 / projects','section.tools':'03 / tools','section.contact':'04 / contact','about.title':'I design expressive<br><em>systems.</em>','about.body':'I am a Computer Science graduate from the University of Brasília (UnB), specializing in creative technology and game development. I served as principal programmer and game designer on Dream Delirio’s and XIII — A Final Game of Tarot with Death. XIII is available on Steam, while Dream Delirio’s has a Steam page and a playable demo. My work spans gameplay systems, Unity and Godot development, custom C++/SDL2 engines, shaders, procedural graphics, audio integration with FMOD and Wwise, and performance optimization. I am also a Guest Lecturer in Computer Graphics at UnB.','about.education':'B.Sc. in Computer Science<br><strong>University of Brasília (UnB)</strong>','about.work':'Principal Programmer · Game Designer<br>Dream Delirio’s','about.fira':'Game Development Intern<br>Unity · C#','about.teaching':'Guest Lecturer<br>Computer Graphics · UnB','projects.title':'Selected<br><em>work.</em>','skills.languages':'Languages','skills.development':'Development','skills.languagesSpoken':'Spoken languages','skills.spoken':'Native Portuguese · Fluent English · Basic German','print.site':'Online portfolio for a better experience','print.education':'Education · 2020/2—2025/2','print.autonomous':'Independent · 2024—Present','print.fira':'Fira Soft · Nov 2024—Nov 2025','print.teaching':'Teaching · 2026.2—Present','print.languages':'C, C++, Rust, Python, JavaScript, TypeScript, GDScript, GLSL, HLSL and Assembly RISC-V. Shader programming, graphics programming and performance optimization.','print.development':'Unity, Godot, Raylib, SDL2, OpenGL, WebGL, Vulkan, FMOD, Wwise, Git, Blender, Fusion 360, SQL, HTML/CSS, Steam, Xbox, Itch.io and procedural generation.','contact.title':'Let’s make<br><em>something playable.</em>','contact.lede':'Open to freelance work, collaborations, and conversations about creative technology and real-time graphics.'},
  pt: {'nav.about':'Sobre','nav.projects':'Projetos','nav.contact':'Contato','nav.pdf':'Baixar PDF','hero.eyebrow':'Artista técnico · engenheiro gráfico · aspirante a VJ','hero.lede':'Construo sistemas jogáveis, ferramentas visuais e gráficos expressivos em tempo real.','hero.roles':'desenvolvimento de jogos · design · computação gráfica','hero.cta':'Ver projetos <span aria-hidden="true" class="arrow arrow-down"></span>','hero.contact':'Chama aí!! <span aria-hidden="true" class="arrow arrow-up"></span>','section.about':'01 / sobre','section.projects':'02 / projetos','section.tools':'03 / ferramentas','section.contact':'04 / contato','about.title':'Projeto sistemas<br><em>expressivos.</em>','about.body':'Sou formado em Ciência da Computação pela Universidade de Brasília (UnB), com foco em tecnologia criativa e desenvolvimento de jogos. Atuei como principal programador e game designer em Dream Delirio’s e XIII — A Final Game of Tarot with Death. XIII está disponível na Steam, enquanto Dream Delirio’s possui uma página na Steam e uma demo jogável. Meu trabalho abrange sistemas de gameplay, desenvolvimento em Unity e Godot, engines próprias em C++/SDL2, shaders, gráficos procedurais, integração de áudio com FMOD e Wwise e otimização de performance. Sou professor convidado de Computação Gráfica na UnB.','about.education':'Bacharelado em Ciência da Computação<br>Universidade de Brasília (UnB)','about.work':'Principal Programmer · Game Designer<br>Dream Delirio’s','about.fira':'Estágio em desenvolvimento de jogos<br>Unity · C#','about.teaching':'Professor convidado<br>Computação Gráfica · UnB','projects.title':'Trabalhos<br><em>selecionados.</em>','skills.languages':'Linguagens','skills.development':'Desenvolvimento','skills.languagesSpoken':'Idiomas','skills.spoken':'Português nativo · Inglês fluente · Alemão básico','print.site':'Portfólio online','print.education':'Educação · 2020/2—2025/2','print.autonomous':'Independente · 2024—Presente','print.fira':'Fira Soft · Nov 2024—Nov 2025','print.teaching':'Ensino · 2026.2—Presente','print.languages':'C, C++, C#, Rust, Python, JavaScript, TypeScript, GDScript, GLSL, HLSL e Assembly RISC-V. Programação de shaders, computação gráfica e otimização de performance.','print.development':'Unity, Godot, Raylib, SDL2, OpenGL, WebGL, Vulkan, FMOD, Wwise, Git, Blender, Fusion 360, SQL, HTML/CSS, Steam, Xbox, Itch.io e geração procedural.','contact.title':'Vamos fazer<br><em>algo jogar.</em>','contact.lede':'Aberto a trabalhos freelance, colaborações e conversas sobre tecnologia criativa e gráficos em tempo real.'}
};

translations.en['print.languages'] = 'C, C++, C#, Rust, Python, JavaScript, TypeScript, GDScript, GLSL, HLSL and Assembly RISC-V. Shader programming, graphics programming and performance optimization.';
translations.en['print.site'] = 'Online portfolio';
translations.pt['print.site'] = 'Portfólio online';
translations.en['print.siteCta'] = 'View the online portfolio for the complete experience ↗';
translations.pt['print.siteCta'] = 'Veja o portfólio online para uma experiência completa ↗';

const bilingual = (en, pt) => ({ en, pt });
const media = (source, overrides = {}) => ({ source, printSource: source, fit: 'cover', printFit: 'cover', position: 'center', printPosition: 'center', ...overrides });
export const projects = [
  {title:bilingual('Dream Delirio’s','Dream Delirio’s'),media:media('dream-delirios-print.png'),description:bilingual('A psychedelic arena shooter where breakfast becomes weaponry. I led programming and game design across gameplay systems, procedural waves, cards, UI, shaders and FMOD audio.','Twin-stick shooter de arena psicodélico em que o café da manhã vira arma. Atuei como principal programador e game designer nos sistemas de gameplay, waves procedurais, cartas, UI, shaders e áudio com FMOD.'),tags:['Unity','Game systems'],links:[{label:'Steam',url:'https://store.steampowered.com/app/3692710/Dream_Delirios/'}],tone:'indigo'},
  {title:bilingual('XIII — A Final Game of Tarot with Death','XIII — A Final Game of Tarot with Death'),media:media('xiii-xbox.jpg'),description:bilingual('Winner of Game Jam UnB and later released on Steam and Xbox. Principal Programmer and Game Designer with a focus on UI/UX and graphics.','Vencedor da Game Jam UnB e posteriormente lançado na Steam e no Xbox. Atuação como principal programador e game designer, com foco em UI/UX e programação gráfica.'),tags:['UI/UX','Graphics'],links:[{label:'View Steam',url:'https://store.steampowered.com/app/3381140/XIII__A_Final_Game_of_Tarot_With_Death/'},{label:'View Xbox',url:'https://www.xbox.com/en-us/games/store/xiii-a-final-game-of-tarot/9NP0N8DM0L6B'}],tone:'violet'},
  {title:bilingual('Design. Velocity. Death.','Design. Velocity. Death.'),media:media('dvd-design-velocity-death.png'),description:bilingual('A fast-paced endless runner made for GMTK Game Jam. Pilot a ship through an endless track, dodge obstacles and collect boosters to keep the run alive.','Endless runner acelerado feito para a GMTK Game Jam. Pilote uma nave por uma pista infinita, desvie de obstáculos e colete boosters para manter a partida.'),tags:['Unity','Procedural graphics'],links:[{label:'Itch.io',url:'https://r4zputin.itch.io/design-velocity-death'}],tone:'pink'},
  {title:bilingual('Hunger','Hunger'),media:media('hunger-print.jpg'),description:bilingual('Built in a custom C++ engine over two months. Solo programmer in a team with four artists. Winner of Best Game, Best Art and Best Implementation at UnB’s 11th Digital Games Exhibition.','Desenvolvido em uma engine própria em C++ ao longo de dois meses. Programador solo em uma equipe com quatro artistas. Recebeu os prêmios de Melhor Jogo, Melhor Arte e Melhor Implementação na 11ª Exibição de Jogos Digitais da UnB.'),tags:['C++','Custom engine'],links:[{label:'GitHub',url:'https://github.com/Felipedbbsb/Hunger-Game'},{label:'YouTube',url:'https://youtu.be/Vol31olD0_I'}],tone:'red'},
  {title:bilingual('Retro Arsenal','Retro Arsenal'),media:media('retro-arsenal-profile.png'),description:bilingual('A 2.5D boomer shooter made for Game Jam Plus. I contributed to gameplay design and implementation in a team combining 2D and 3D art.','Boomer shooter 2.5D feito para a Game Jam Plus. Contribuí para o design e a implementação de mecânicas em uma equipe que combinou arte 2D e 3D.'),tags:['Unity','Gameplay'],links:[{label:'Itch.io',url:'https://iurisevero.itch.io/retro-arsenal'}],tone:'orange'},
  {title:bilingual('Chroma','Chroma'),media:media('chroma-print.jpg'),description:bilingual('A browser-based tool for learning computer graphics through live vertex and fragment shader editing. It combines Three.js rendering, theory tabs, textures, geometry and camera controls, project save/load and compile feedback.','Ferramenta de navegador para aprender computação gráfica com edição ao vivo de vertex e fragment shaders. Combina renderização com Three.js, abas de teoria, texturas, controles de geometria e câmera, salvar/carregar projetos e feedback de compilação.'),tags:['Three.js','GLSL','Shader tools'],links:[{label:'Demo',url:'https://gustavo-tomas.github.io/Chroma/'},{label:'GitHub',url:'https://github.com/gustavo-tomas/Chroma'}],tone:'cyan'},
  {title:bilingual('Plush Time','Plush Time'),media:media('plush-time-header.jpg'),description:bilingual('Contracted to enhance game feel across minigames through juice, special effects and player-experience improvements for this 1–6 player local and online party game.','Contratado para elevar o game feel dos minigames com juice, efeitos especiais e melhorias na experiência dos jogadores neste party game local e online para 1–6 jogadores.'),tags:['Game Feel','Unity'],links:[{label:'View Steam',url:'https://store.steampowered.com/app/3764040/Plush_Time/'}],tone:'pink'}
];
