export const projects = [
  { year: '2024—25', title: 'Dream Delirio’s', type: 'Twin-stick shooter roguelike', image: 'image-011.jpg', description: 'Jogo inspirado em desenhos latino-americanos. Atuação como programmer e game designer, com foco em sistemas de jogo e experiência do jogador.', tags: ['Unity', 'Game design'], links: [] },
  { year: '2024', title: 'XIII — A Final Game of Tarot with Death', type: 'Psychedelic roguelike card game', image: 'image-007.jpg', description: 'Projeto vencedor da Game Jam UnB 2024 e posteriormente lançado na Steam. Atuação em UI/UX e programação gráfica.', tags: ['Unity', 'UI/UX', 'Steam'], links: [{ label: 'Steam', url: 'https://store.steampowered.com/' }] },
  { year: '2024', title: 'Retro Arsenal', type: 'FPS retro style', image: 'image-016.jpg', description: 'Vencedor da GJ+ 2024/2025 em Brasília. Projeto em desenvolvimento com atuação em UI/UX e programação gráfica.', tags: ['Unity', 'UI/UX', 'Itch.io'], links: [{ label: 'Itch.io', url: 'https://itch.io/' }] },
  { year: '2023', title: 'Hunger', type: 'Estratégia 2D · roguelike', image: 'image-005.jpg', description: 'Jogo desenvolvido em uma engine própria programada em C++, ao longo de dois meses. Programador solo em uma equipe com quatro artistas. Recebeu os prêmios de Melhor Jogo, Melhor Arte e Melhor Implementação na 11ª Exibição de Jogos Digitais da UnB.', tags: ['C++', 'SDL2', 'Engine própria'], links: [{ label: 'GitHub', url: 'https://github.com/' }, { label: 'YouTube', url: 'https://youtube.com/' }] },
  { year: '2023', title: 'Pinguim', type: 'Jogo acadêmico', image: 'image-005.jpg', description: 'Jogo criado para a disciplina de Introdução ao Desenvolvimento de Jogos da Universidade de Brasília, usando uma engine própria em C++.', tags: ['C++', 'Game programming'], links: [{ label: 'GitHub', url: 'https://github.com/' }] },
  { year: '2022', title: 'Castlevania Remake', type: 'Fanmade · plataforma 2D', image: 'image-002.jpg', description: 'Fanmade de Castlevania: Symphony of the Night, desenvolvido individualmente em duas semanas com uma engine customizada em Assembly RISC-V.', tags: ['Assembly RISC-V', 'Engine própria'], links: [{ label: 'GitHub', url: 'https://github.com/' }] },
  { year: '2021', title: 'Adventures of Lamar', type: 'Fanmade · aventura', image: 'image-001.jpg', description: 'Fanmade de Adventures of Lolo (1989), construído com uma engine customizada programada em Assembly RISC-V.', tags: ['Assembly RISC-V', 'Engine própria'], links: [{ label: 'GitHub', url: 'https://github.com/' }] }
];
