export const translations = {
  en: {'nav.about':'About','nav.projects':'Projects','nav.contact':'Contact','nav.pdf':'PDF / resume','hero.eyebrow':'Technical artist · graphics engineer · aspiring VJ','hero.lede':'I build playable systems, visual tools and expressive real-time graphics.','hero.roles':'Game development / programming / design / realtime graphics','hero.cta':'See projects <span>↘</span>','hero.contact':'Get in touch <span>↗</span>','hero.note':'Brasília, Brazil<br><span>Available for projects</span>','section.about':'01 / about','section.projects':'02 / projects','section.tools':'03 / tools','section.contact':'04 / contact','about.title':'I build games<br><em>with intention.</em>','about.body':'I hold a degree in Computer Science from the University of Brasília. My experience covers custom engines, Unity, systems programming, interfaces, graphics and game design.','about.education':'Computer Science<br>University of Brasília','about.work':'Game development<br>and digital experiences','projects.title':'Selected<br><em>work.</em>','projects.description':'A selection of projects developed between 2021 and 2025, from custom engines to published games.','skills.languages':'Languages','skills.development':'Development','skills.languagesSpoken':'Spoken languages','skills.spoken':'Native Portuguese · Fluent English · Basic German','contact.title':'Let’s make<br><em>something playable.</em>'},
  pt: {'nav.about':'Sobre','nav.projects':'Projetos','nav.contact':'Contato','nav.pdf':'PDF / currículo','hero.eyebrow':'Artista técnico · engenheiro gráfico · aspirante a VJ','hero.lede':'Construo sistemas jogáveis, ferramentas visuais e gráficos expressivos em tempo real.','hero.roles':'desenvolvimento de jogos / programação / design / gráficos em tempo real','hero.cta':'Ver projetos <span>↘</span>','hero.contact':'Entrar em contato <span>↗</span>','hero.note':'Brasília, Brasil<br><span>Disponível para projetos</span>','section.about':'01 / sobre','section.projects':'02 / projetos','section.tools':'03 / ferramentas','section.contact':'04 / contato','about.title':'Construo jogos<br><em>com intenção.</em>','about.body':'Sou bacharel em Ciência da Computação pela Universidade de Brasília. Minha experiência passa por engines próprias, Unity, programação de sistemas, interface, gráficos e design de jogos.','about.education':'Ciência da Computação<br>Universidade de Brasília','about.work':'Desenvolvimento de jogos<br>e experiências digitais','projects.title':'Trabalhos<br><em>selecionados.</em>','projects.description':'Uma seleção de projetos desenvolvidos entre 2021 e 2025, de engines customizadas a jogos publicados.','skills.languages':'Linguagens','skills.development':'Desenvolvimento','skills.languagesSpoken':'Idiomas','skills.spoken':'Português nativo · Inglês fluente · Alemão básico','contact.title':'Vamos fazer<br><em>algo jogar.</em>'}
};

const bilingual = (en, pt) => ({ en, pt });
export const projects = [
  {year:'2024—25',title:bilingual('Dream Delirio’s','Dream Delirio’s'),type:bilingual('Twin-stick shooter roguelike','Twin-stick shooter roguelike'),image:'image-011.jpg',description:bilingual('A game inspired by Latin American cartoons. Programmer and game designer, focused on game systems and player experience.','Jogo inspirado em desenhos latino-americanos. Atuação como programmer e game designer, com foco em sistemas de jogo e experiência do jogador.'),tags:['Unity','Game design','Twin-stick shooter','Roguelike','Card synergies','Systems design'],links:[{label:'View on Steam',url:'https://store.steampowered.com/app/3692710/Dream_Delirios/'}],tone:'indigo'},
  {year:'2024',title:bilingual('XIII — A Final Game of Tarot with Death','XIII — A Final Game of Tarot with Death'),type:bilingual('Psychedelic roguelike card game','Roguelike de cartas psicodélico'),image:'image-007.jpg',description:bilingual('Winner of Game Jam UnB 2024 and later released on Steam. UI/UX and graphics programmer.','Vencedor da Game Jam UnB 2024 e posteriormente lançado na Steam. Atuação em UI/UX e programação gráfica.'),tags:['Unity','UI/UX','Graphics programming','Roguelike','Card game','Game Jam winner'],links:[{label:'View on Steam',url:'https://store.steampowered.com/app/3381140/XIII__A_Final_Game_of_Tarot_With_Death/'}],tone:'violet'},
  {year:'2024',title:bilingual('Retro Arsenal','Retro Arsenal'),type:bilingual('Retro-style FPS','FPS retro style'),image:'image-016.jpg',description:bilingual('Winner of GJ+ 2024/2025 in Brasília. In development, with UI/UX and graphics programming work.','Vencedor da GJ+ 2024/2025 em Brasília. Projeto em desenvolvimento com atuação em UI/UX e programação gráfica.'),tags:['Unity','UI/UX','Graphics programming','FPS','Retro aesthetic','Game Jam winner'],links:[{label:'Play on Itch.io',url:'https://itch.io/'}],tone:'orange'},
  {year:'2023',title:bilingual('Hunger','Hunger'),type:bilingual('2D strategy · roguelike','Estratégia 2D · roguelike'),image:'image-005.jpg',description:bilingual('Built in a custom C++ engine over two months. Solo programmer in a team with four artists. Winner of Best Game, Best Art and Best Implementation at UnB’s 11th Digital Games Exhibition.','Desenvolvido em uma engine própria em C++ ao longo de dois meses. Programador solo em uma equipe com quatro artistas. Recebeu os prêmios de Melhor Jogo, Melhor Arte e Melhor Implementação na 11ª Exibição de Jogos Digitais da UnB.'),tags:['C++','SDL2','Custom engine','Strategy game','Roguelike','Solo programmer','Best Game award'],links:[{label:'GitHub',url:'https://github.com/Felipedbbsb/Hunger-Game'},{label:'YouTube',url:'https://youtu.be/Vol31olD0_I'}],tone:'red'},
  {year:'2022',title:bilingual('Castlevania Remake','Castlevania Remake'),type:bilingual('Fanmade · 2D platformer','Fanmade · plataforma 2D'),image:'image-002.jpg',description:bilingual('A fanmade version of Castlevania: Symphony of the Night, developed individually in two weeks with a custom Assembly RISC-V engine.','Fanmade de Castlevania: Symphony of the Night, desenvolvido individualmente em duas semanas com uma engine customizada em Assembly RISC-V.'),tags:['Assembly RISC-V','Custom engine','2D platformer','Fan project','Solo project'],links:[{label:'GitHub',url:'https://github.com/'}],tone:'blue'},
  {year:'2025',title:bilingual('Design. Velocity. Death.','Design. Velocity. Death.'),type:bilingual('Psychedelic endless runner','Endless runner psicodélico'),image:'dvd-design-velocity-death.png',description:bilingual('A fast-paced endless runner made with Indigo Dreams for GMTK Game Jam 2025. Pilot a ship through an endless track, dodge obstacles and collect boosters to keep the run alive.','Endless runner acelerado feito pela Indigo Dreams para a GMTK Game Jam 2025. Pilote uma nave por uma pista infinita, desvie de obstáculos e colete boosters para manter a partida.'),tags:["Indigo Dreams","Unity","Endless runner","Racing","Game Maker's Toolkit Jam","Procedural track","Itch.io"],links:[{label:'Play on Itch.io',url:'https://r4zputin.itch.io/design-velocity-death'}],tone:'pink'},
  {year:'2025',title:bilingual('Chroma','Chroma'),type:bilingual('Accessibility tool','Ferramenta de acessibilidade'),image:'chroma.svg',description:bilingual('A color and accessibility focused project exploring real-time visual feedback, readable interfaces and chromatic systems.','Projeto focado em cor e acessibilidade, explorando feedback visual em tempo real, interfaces legíveis e sistemas cromáticos.'),tags:['C#','Unity','Accessibility','Color systems','Shader programming','UI/UX','Tools'],links:[{label:'Project details',url:'https://github.com/Felipedbbsb'}],tone:'cyan'}
];
